# workflow name
name: Build avl6381 Driver (PandoraBox-19.01-ralink-mt7620)

# trigger the workflow manually from the GitHub UI
on:
  workflow_dispatch:

# Define a single job named 'build'
jobs:
  build:
    # use a Linux runner
    runs-on: ubuntu-latest
    
    # steps to be executed in the job
    steps:
      # step 1: check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # step 2: download and extract the ImmortalWrt SDK
      - name: Download and Extract SDK
        run: |
          wget http://downloads.pangubox.com:6380/pandorabox/19.01/targets/ralink/mt7620/PandoraBox-SDK-ralink-mt7620_gcc-5.5.0_uClibc-1.0.x.Linux-x86_64-2018-12-31-git-4b6a3d5ca.tar.xz
          tar xvf PandoraBox-SDK-ralink-mt7620_gcc-5.5.0_uClibc-1.0.x.Linux-x86_64-2018-12-31-git-4b6a3d5ca.tar.xz

      # step 3: compile the driver
      # all compilation steps are combined into one run block
      - name: Compile Driver
        # set environment variables and run make commands
        run: |
          # The SDK is extracted, so we can define its path
          SDK_DIR=$(pwd)/PandoraBox-SDK-ralink-mt7620_gcc-5.5.0_uClibc-1.0.x.Linux-x86_64-2018-12-31-git-4b6a3d5ca

          # Set the environment variables as per the instructions
          export ARCH=mips
          export STAGING_DIR="${SDK_DIR}/staging_dir/toolchain-mipsel_24kec+dsp_gcc-5.5.0_uClibc-1.0.x/bin/"
          export KERNEL_DIR="${SDK_DIR}/build_dir/target-mipsel_24kec+dsp_uClibc-1.0.x/linux-ralink_mt7620/linux-3.14.79"
          export TOOLCHAIN="${SDK_DIR}/staging_dir/toolchain-mipsel_24kec+dsp_gcc-5.5.0_uClibc-1.0.x/bin/mipsel-openwrt-linux-"
          
          # Check if the directories exist before compiling
          ls -l $STAGING_DIR
          ls -l $KERNEL_DIR
          
          # Run the compilation steps
          make prepare
          make

      # step 4: create a directory for the compiled modules and copy the files
      - name: Stage compiled modules
        run: |
          mkdir -p build/ko_modules
          cp /home/runner/work/avl6381/avl6381/*.{ko,o} build/ko_modules/
          ls -l build/ko_modules/

      # step 5: upload the directory as a workflow artifact
      - name: Upload Driver as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: avl6381-driver-modules
          path: build/ko_modules
