# workflow name
name: Build avl6381 Driver (Ubuntu 5.4.0-216)

# trigger the workflow manually from the GitHub UI
on:
  workflow_dispatch:

# Define a single job named 'build'
jobs:
  build:
    # use a Linux runner
    runs-on: ubuntu-latest
    
    # steps to be executed in the job
    steps:
      # step 1: check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # step 2: download and install the kernel headers for Ubuntu 5.4.0-216
      - name: Download and Install Ubuntu Kernel Headers
        run: |
          # Install necessary packages for building from source
          sudo apt-get update
          sudo apt-get install -y build-essential
          
          # Download and install libssl1.1 manually to resolve dependency issue
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
          sudo dpkg -i ./libssl1.1_1.1.0g-2ubuntu4_amd64.deb
          
          # Download the specific kernel headers and image from Ubuntu archives
          # The URLs are for the 5.4.0-216.236 version on Launchpad
          wget http://launchpadlibrarian.net/787680584/linux-headers-5.4.0-216-generic_5.4.0-216.236_amd64.deb
          wget https://launchpad.net/~canonical-kernel-team/+archive/ubuntu/ppa/+build/30625263/+files/linux-headers-5.4.0-216_5.4.0-216.236_all.deb
          wget https://launchpad.net/~canonical-kernel-team/+archive/ubuntu/ppa/+build/30625263/+files/linux-image-unsigned-5.4.0-216-generic_5.4.0-216.236_amd64.deb
          w
